"""initial

Revision ID: 4f7a23014b59
Revises: 
Create Date: 2025-01-15 18:08:42.301179

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "4f7a23014b59"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "event",
        sa.Column("coefficient", sa.DECIMAL(precision=7, scale=2), nullable=False),
        sa.Column("deadline", sa.TIMESTAMP(), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM("PENDING", "FIRST_WIN", "SECOND_WIN", name="event_status"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=False),
        sa.CheckConstraint("coefficient > 0", name="check_coefficient_positive"),
        sa.PrimaryKeyConstraint("id", name="event_pkey"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("event")
    # ### end Alembic commands ###
