# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import line_provider_pb2 as line__provider__pb2

GRPC_GENERATED_VERSION = "1.66.1"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in line_provider_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class LineProviderStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetEvents = channel.unary_unary(
            "/line_provider.LineProvider/GetEvents",
            request_serializer=line__provider__pb2.GetEventsRequest.SerializeToString,
            response_deserializer=line__provider__pb2.GetEventsResponse.FromString,
            _registered_method=True,
        )
        self.CheckIfEventExists = channel.unary_unary(
            "/line_provider.LineProvider/CheckIfEventExists",
            request_serializer=line__provider__pb2.CheckIfEventExistsRequest.SerializeToString,
            response_deserializer=line__provider__pb2.EventResponse.FromString,
            _registered_method=True,
        )


class LineProviderServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CheckIfEventExists(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_LineProviderServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetEvents": grpc.unary_unary_rpc_method_handler(
            servicer.GetEvents,
            request_deserializer=line__provider__pb2.GetEventsRequest.FromString,
            response_serializer=line__provider__pb2.GetEventsResponse.SerializeToString,
        ),
        "CheckIfEventExists": grpc.unary_unary_rpc_method_handler(
            servicer.CheckIfEventExists,
            request_deserializer=line__provider__pb2.CheckIfEventExistsRequest.FromString,
            response_serializer=line__provider__pb2.EventResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "line_provider.LineProvider", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "line_provider.LineProvider", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class LineProvider(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetEvents(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/line_provider.LineProvider/GetEvents",
            line__provider__pb2.GetEventsRequest.SerializeToString,
            line__provider__pb2.GetEventsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def CheckIfEventExists(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/line_provider.LineProvider/CheckIfEventExists",
            line__provider__pb2.CheckIfEventExistsRequest.SerializeToString,
            line__provider__pb2.EventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
