# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: line_provider.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x13line_provider.proto\x12\rline_provider"\x12\n\x10GetEventsRequest"A\n\x11GetEventsResponse\x12,\n\x06\x65vents\x18\x01 \x03(\x0b\x32\x1c.line_provider.EventResponse"z\n\rEventResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x13\n\x0b\x63oefficient\x18\x02 \x01(\x02\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\x10\n\x08\x64\x65\x61\x64line\x18\x04 \x01(\t\x12\x12\n\ncreated_at\x18\x05 \x01(\t\x12\x12\n\nupdated_at\x18\x06 \x01(\t"-\n\x19\x43heckIfEventExistsRequest\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t2\xc0\x01\n\x0cLineProvider\x12P\n\tGetEvents\x12\x1f.line_provider.GetEventsRequest\x1a .line_provider.GetEventsResponse"\x00\x12^\n\x12\x43heckIfEventExists\x12(.line_provider.CheckIfEventExistsRequest\x1a\x1c.line_provider.EventResponse"\x00\x42\x11Z\x0f./line_providerb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "line_provider_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals["DESCRIPTOR"]._serialized_options = b"Z\017./line_provider"
    _globals["_GETEVENTSREQUEST"]._serialized_start = 38
    _globals["_GETEVENTSREQUEST"]._serialized_end = 56
    _globals["_GETEVENTSRESPONSE"]._serialized_start = 58
    _globals["_GETEVENTSRESPONSE"]._serialized_end = 123
    _globals["_EVENTRESPONSE"]._serialized_start = 125
    _globals["_EVENTRESPONSE"]._serialized_end = 247
    _globals["_CHECKIFEVENTEXISTSREQUEST"]._serialized_start = 249
    _globals["_CHECKIFEVENTEXISTSREQUEST"]._serialized_end = 294
    _globals["_LINEPROVIDER"]._serialized_start = 297
    _globals["_LINEPROVIDER"]._serialized_end = 489
# @@protoc_insertion_point(module_scope)
